# Generated by Django 5.2.11 on 2026-03-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tansactionmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
