# Generated by Django 5.2.11 on 2026-03-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_at',
            field=models.DateField(),
        ),
    ]
