# Generated by Django 5.2.11 on 2026-04-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_categorymodel_category_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='category_at',
            new_name='created_at',
        ),
    ]
