# Generated by Django 5.2.11 on 2026-04-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_rename_category_at_categorymodel_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='name',
            new_name='category_name',
        ),
    ]
